//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUG.Packages.KBCodeReview {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUG.Packages.KBCodeReview.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About KBCodeReview.
        /// </summary>
        internal static string AboutKBCodeReview {
            get {
                return ResourceManager.GetString("AboutKBCodeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help KBCodeReview.
        /// </summary>
        internal static string HelpKBCodeReview {
            get {
                return ResourceManager.GetString("HelpKBCodeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;text&quot;/&gt;
        ///
        ///
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;xsl:text&gt;Text Format Navigation for KBDoctor version 10.8&lt;/xsl:text&gt;
        ///    &lt;xsl:apply-templates select=&quot;ObjectSpec&quot;/&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;xsl:variable name=&quot;Product&quot; select=&quot;KBdoctor&quot;/&gt;
        ///  &lt;xsl:variable name=&quot;Images&quot;  select=&quot;Images&quot;/&gt;
        ///
        ///  &lt;xsl:template name=&quot;TableHeaderMain&quot;&gt;
        ///    &lt;xsl:param name=&quot;title&quot;&gt;Table Title&lt;/xsl:param&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NavigationHTMLtoText {
            get {
                return ResourceManager.GetString("NavigationHTMLtoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export objects in text format.
        /// </summary>
        internal static string ObjectInTextFormat {
            get {
                return ResourceManager.GetString("ObjectInTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder KBCodeReview.
        /// </summary>
        internal static string OpenFolderKBCodeReview {
            get {
                return ResourceManager.GetString("OpenFolderKBCodeReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Changes.
        /// </summary>
        internal static string PushChanges {
            get {
                return ResourceManager.GetString("PushChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Diff.
        /// </summary>
        internal static string SendDiff {
            get {
                return ResourceManager.GetString("SendDiff", resourceCulture);
            }
        }
    }
}
